labdbms/app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('account','AccountController');
Route::resource('product','ProductController');
Route::resource('categories','CategoriesController');
Route::resource('export','ExportController');
Route::resource('borrow','BorrowController');
Route::resource('insertproduct','InsertProductController');
Route::resource('addexport','AddExportController');
Route::resource('addborrow','AddBorrowController');
Route::resource('employee','EmployeeController');
Route::resource('editemployee','EditEmployeeController');
Route::resource('editexport','EditExportController');
Route::resource('editborrow','EditBorrowController');
Route::resource('editproduct','EditProductController');
Route::resource('exportdetail','ExportDetailController');

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/account', function () {
//     return view('account.index');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

labdbms/app/app/Export.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Export extends Model
{
    protected $table = 'Exports';
    protected $fillable = ['exp_id','approve_emp_id','exp_date','exp_id','prod_id','exp_qty','request_emp_id'];

}

labdbms/app/app/Http/Controllers/ExportController.php
<?php

namespace App\Http\Controllers;

use DB;
use Illuminate\Http\Request;
use App\Export;

class ExportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  SELECT * FROM Exports LEFT JOIN Export_details ON Exports.exp_id = Export_details.exp_id


        $export = DB::table('Exports')
            ->leftJoin('Employees', 'Employees.emp_id', '=', 'Exports.approve_emp_id')
            ->get();
กำลังจะ เอา รีเควส

SELECT * FROM Exports e 
JOIN Export_details d ON e.exp_id = d.exp_id 
JOIN Products p ON p.prod_id = d.prod_id 
JOIN Employees m ON d.request_emp_id = m.emp_id
WHERE e.exp_id='x0001'




        return view('export.export',compact('export'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('export.addExport');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
       
       
       
        $request->validate(
            [
                'exp_id' => 'required|max:5',
                'approve_emp_id' => 'required|max:5',
                'prod_id' => 'required|max:5',
                'exp_qty' => 'required',
                'request_emp_id' => 'required|max:5',
            ],
            [
                'exp_id.required' => 'กรุณาใส่รหัสใบเบิกสินค้า',
                'exp_id.max' => 'รหัสใบเบิกสินค้าต้องใส่จำนวน 5 ตัวอักษร',
                'approve_emp_id.required' => 'กรุณาใส่รหัสพนักงานที่อนุมัติให้เบิกสินค้า',
                'approve_emp_id.max' => 'รหัสพนักงานที่อนุมัติให้เบิกสินค้า ต้องใส่จำนวน 5 ตัวอักษร',

                'prod_id.required' => 'กรุณาใส่รหัสสินค้า',
                'prod_id.max' => 'รหัสสินค้าใส่ต้องใส่จำนวน 5 ตัวอักษร',

                'exp_qty.required' => 'กรุณาใส่จำนวนของสินค้าที่ต้องการเบิก',
                'request_emp_id.required' => 'กรุณาใส่รหัสพนักงานที่ต้องการเบิกสินค้า',
                'request_emp_id.max' => 'รหัสพนักงานที่ต้องการเบิกสินค้า ต้องใส่จำนวน 5 ตัวอักษร',

            ]


        );
        $export = new Export;
        $export ->exp_id = $request->get('exp_id');
        $export ->approve_emp_id = $request->get('approve_emp_id');
        $export ->exp_date = date('Y-m-d H:i:s');
        $export ->prod_id = $request->get('prod_id');
        $export ->exp_qty = $request->get('exp_qty');
        $export ->request_emp_id = $request->get('request_emp_id');

        $export ->save();
        return redirect('export');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $export = DB::table('Employees')
            ->join('Export_details', 'Employees.emp_id', '=', 'Export_details.request_emp_id')
            ->join('Products', 'Products.prod_id', '=', 'Export_details.prod_id')
            ->where('Export_details.exp_id', '=', $id)
            ->get();

        return view('export.exportDetail',compact('export'));


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {        
        $export = Export::where('exp_id', $id)->first();
        return view('export.editExport',compact('export'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $export = Export::where('exp_id', $id)->first();
        $request->validate(
            [
                'exp_id' => 'required|max:5',
                'approve_emp_id' => 'required|max:5',
                'prod_id' => 'required|max:5',
                'exp_qty' => 'required',
                'request_emp_id' => 'required|max:5',

            ],
            [
                'exp_id.required' => 'กรุณาใส่รหัสใบเบิกสินค้า',
                'exp_id.max' => 'รหัสใบเบิกสินค้าต้องใส่จำนวน 5 ตัวอักษร',
                'approve_emp_id.required' => 'กรุณาใส่รหัสพนักงานที่อนุมัติให้เบิกสินค้า',
                'approve_emp_id.max' => 'รหัสพนักงานที่อนุมัติให้เบิกสินค้า ต้องใส่จำนวน 5 ตัวอักษร',

                'prod_id.required' => 'กรุณาใส่รหัสสินค้า',
                'prod_id.max' => 'รหัสสินค้าใส่ต้องใส่จำนวน 5 ตัวอักษร',

                'exp_qty.required' => 'กรุณาใส่จำนวนของสินค้าที่ต้องการเบิก',
                'request_emp_id.required' => 'กรุณาใส่รหัสพนักงานที่ต้องการเบิกสินค้า',
                'request_emp_id.max' => 'รหัสพนักงานที่ต้องการเบิกสินค้า ต้องใส่จำนวน 5 ตัวอักษร',

            ]
        );
       
        $export->exp_id = $request->exp_id;
        $export->approve_emp_id = $request->approve_emp_id; 
        $export->exp_date = date('Y-m-d H:i:s');
        $export->prod_id = $request->prod_id;
        $export->exp_qty = $request->exp_qty;
        $export->request_emp_id = $request->request_emp_id;


        DB::table('Exports')->where('exp_id', $id)->update([
            'approve_emp_id' => $request->approve_emp_id,
            'exp_date' => $request->exp_date,
            'prod_id' => $request->prod_id,
            'exp_qty' => $request->exp_qty,
            'request_emp_id' => $request->request_emp_id
            ]);
    
        return redirect()->route('export');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $export = Export::where('exp_id', $id);
        $export->delete();
        return redirect("export");
    }
}

labdbms/app/resources/views/export/addExport.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 700px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="/">หน้าหลัก</a></li>
        <li><a href="/product">สินค้า</a></li>
        <li class="active"><a href="/export">เบิกสินค้า</a></li>
        <li><a href="/borrow">ยืมสินค้า</a></li>
        <li><a href="/employee">พนักงาน</a></li>
      </ul><br>
    </div>
    
    <div class="col-sm-10 text-left"> 

      <div class="row">
        <div class="col-sm-12 text-center">
          <div class="well" style="background-color:rgb(255, 212, 71)">
          <h4>ใบเบิกสินค้า</h4>
          </div>
        </div>
      </div>
      <!-- <h2 text-center>ใบเบิกสินค้า</h2> -->




      <div class="well">
        <table class="table table-condensed">
          <form method="post" action="{{ route('export.store') }}">
              {{ csrf_field() }}
                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">เลขที่ใบเบิก:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control{{ $errors->has('exp_id') ? ' is-invalid' : '' }}"  id="exp_id" placeholder="ACC001" name="exp_id" maxlength="5" >
                      @if($errors->has('exp_id'))
                      <div class="alert alert-danger">
                        <strong>{{ $errors->first('exp_id') }}</strong>
                      </div>
                      @endif
                  </div>
                </div>
                <br>
                <br>

                <div class="form-group">
                  <label class="control-label col-sm-2" for="approve_emp_id">ผู้อนุมัติ:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control{{ $errors->has('approve_emp_id') ? ' is-invalid' : '' }}"  id="approve_emp_id" placeholder="m0001" name="approve_emp_id" maxlength="5">
                      @if($errors->has('approve_emp_id'))
                      <div class="alert alert-danger">
                        <strong>{{ $errors->first('approve_emp_id') }}</strong>
                      </div>
                      @endif
                  </div>
                </div>
                <br>
                <br>

                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="prod_id">รหัสของสินค้า:</label>
                  <div class="col-sm-4">
                      <input type="text" class="form-control{{ $errors->has('prod_id') ? ' is-invalid' : '' }}"  id="prod_id" placeholder="P0001" name="prod_id" maxlength="5">
                      @if($errors->has('prod_id'))
                      <div class="alert alert-danger">
                        <strong>{{ $errors->first('prod_id') }}</strong>
                      </div>
                      @endif
                  </div>


                  <label class="control-label col-sm-1" for="exp_qty">จำนวน:</label>
                  <div class="col-sm-4">
                      <input type="number" class="form-control{{ $errors->has('exp_qty') ? ' is-invalid' : '' }}"  id="exp_qty" placeholder="5" name="exp_qty">
                      @if($errors->has('exp_qty'))
                      <div class="alert alert-danger">
                        <strong>{{ $errors->first('exp_qty') }}</strong>
                      </div>
                      @endif
                  </div>
                  <label class="control-label col-sm-1" >ชิ้น</label>

                </div>  

                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="request_emp_id">ผู้เบิก:</label>
                  <div class="col-sm-10">
                      <input type="text" class="form-control{{ $errors->has('request_emp_id') ? ' is-invalid' : '' }}"  id="request_emp_id" placeholder="m0002" name="request_emp_id" maxlength="5">
                      @if($errors->has('request_emp_id'))
                      <div class="alert alert-danger">
                        <strong>{{ $errors->first('request_emp_id') }}</strong>
                      </div>
                      @endif
                  </div>
                </div>
                <br>
                <br>
                <div class="form-group" text-center>
                <label class="col-sm-4"> </label>
                  <button type="submit" class="btn btn-primary col-sm-4 ">บันทึก</button>   
                <label class="col-sm-4"> </label>
        
                </div>

          </form> 
        </table>
      </div>
    </div>
  </div>
</div>
<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>


</body>
</html>

labdbms/app/resources/views/export/editExport.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 700px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="/">หน้าหลัก</a></li>
        <li><a href="/product">สินค้า</a></li>
        <li class="active"><a href="/export">เบิกสินค้า</a></li>
        <li><a href="/borrow">ยืมสินค้า</a></li>
        <li><a href="/employee">พนักงาน</a></li>
      </ul><br>
    </div>
    <div class="col-sm-10 text-left"> 


      <div class="well">
        <h4>ใบเบิกสินค้า</h4>
      </div>

      <div class="well">
        <form method="post" action="{{ route('export.update',$export->id)  }}">
        @csrf
        @method("PUT")
          <div class="form-group">
            <label for="exp_id">เลขที่ใบเบิก</label>
            <input type="text" name="exp_id" class="form-countrol">
          </div>
          <div class="form-group">
            <label for="exp_date">วันที่เบิกสินค้า</label>
            <input type="datetime-local" name="exp_date" class="form-countrol">
          </div>

          <div class="form-group">
            <label for="approve_emp_id">ผู้อนุมัติ</label>
            <input type="text" name="approve_emp_id" class="form-countrol">
          </div>
          <div>
            <button type="submit" class="btn btn-default">แก้ไข</button>                   
          </div>
        </form>
      </div>



    </div>


    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>


</body>
</html>

labdbms/app/resources/views/export/export.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Export</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 700px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
    .button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    }
    .button1 {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);
    }
  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="/">หน้าหลัก</a></li>
        <li><a href="/product">สินค้า</a></li>
        <li class="active"><a href="/export">เบิกสินค้า</a></li>
        <li><a href="/borrow">ยืมสินค้า</a></li>
        <li><a href="/employee">พนักงาน</a></li>
      </ul><br>
    </div>

    <div class="col-sm-10 text-left"> 
      <div class="row">
        <div class="col-sm-9 text-center">
          <div class="well">
            <h4>การเบิกสินค้า</h4>
          </div>
        </div>
        <div class="col-sm-3">
          <a href="{{ route('export.create') }}" class="button button1">เพิ่มใบเบิกสินค้า</a>
        </div>
      </div>

      <div class="col-sm-12"  >
        <div class="well" style="background-color:Tomato;">
          <h4>ของใช้สำนักงาน</h4> 
        </div>
      </div>

      <div class="well">
        <table class="table table-condensed">
          <thead>
            <tr>
              <th scope="col">เลขที่ใบเบิก</th>
              <th scope="col">วันที่เบิกสินค้า</th>
              <th scope="col">ชื่อผู้อนุมัติ</th>
              <!-- <th scope="col">รายการสินค้า</th>
              <th scope="col">จำนวนสินค้า</th> -->
              <!-- <th scope="col">ราคารวม</th>
              <th scope="col">ผู้เบิก</th>
              <th scope="col">ผู้อนุมัติ</th> -->


              <th>จัดการข้อมูล</th>
            </tr>
          </thead>
          @foreach($export as $row)
          <tr>
            <td class="col-sm-2">{{ $row->exp_id }}</td>
            <td class="col-sm-2">{{ $row->exp_date }}</td>
            <td class="col-sm-2">{{ $row->emp_fname }} {{ $row->emp_lname }}</td>

            <td class="col-sm-1"><a href="{{ route('export.show',$row->exp_id) }}" class="btn btn-info"><span class="glyphicon glyphicon-list-alt"> ดูรายละเอียด</span></a></td>
            <td class="col-sm-1"><a href="{{ route('export.edit',$row->exp_id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span> แก้ไข</a></td>
            <td class="col-sm-1"><form action="{{ route('export.destroy',$row->exp_id) }}" method="post">
            @csrf
            @method("DELETE")
            <button class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> ลบ</button></form></td>


          </tr>
          @endforeach
         

        </table>
      </div>
    </div>

   
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>


</body>
</html>

labdbms/app/resources/views/export/exportDetail.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height:auto}
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: auto;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }
  </style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
      </ul>
    </div>
  </div>
</nav>
  
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li><a href="/">หน้าหลัก</a></li>
        <li><a href="/product">สินค้า</a></li>
        <li class="active"><a href="/export">เบิกสินค้า</a></li>
        <li><a href="/borrow">ยืมสินค้า</a></li>
        <li><a href="/employee">พนักงาน</a></li>
      </ul><br>
    </div>
    @foreach($export as $row)

    <div class="col-sm-10 text-left"> 

      <div class="row">
        <div class="col-sm-12 text-center">
          <div class="well" style="background-color:LightBlue ">
          <h3>ใบเบิกสินค้า {{ $row->exp_id }}</h3>
          </div>
        </div>
      </div>

      <div class="well">
        <table class="table table-condensed">

                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">วันที่เบิก: </label>
                  <div class="col-sm-10">

                  </div>
                </div>
                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">รหัสสินค้า: {{ $row->prod_id }}</label>
                  <div class="col-sm-10">

                  </div>
                </div>

                <br>
                <br>

                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">ชื่อสินค้า: {{ $row->prod_name }}</label>
                  <div class="col-sm-10">

                  </div>
                </div>

                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">จำนวนสินค้า: {{ $row->exp_qty }}</label>
                  <div class="col-sm-10">

                  </div>
                </div>


                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">ผู้เบิก: {{ $row->emp_fname }} {{ $row->emp_lname }}</label>
                  <div class="col-sm-10">

                  </div>
                </div>

                <br>
                <br>
                <div class="form-group">
                  <label class="control-label col-sm-2" for="exp_id">ผู้อนุมัติ: </label>
                  <div class="col-sm-10">

                  </div>
                </div>



        </table>
      </div>




    </div>


    @endforeach

  </div>
</div>
<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>











</body>
</html>